// <auto-generated />
using System;
using AuditNode.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuditNode.Infrastructure.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    partial class AuditDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuditNode.Domain.Entities.AppDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConnectionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("connection_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DestAppId")
                        .HasColumnType("uuid")
                        .HasColumnName("dest_app_id");

                    b.Property<Guid>("DestPortId")
                        .HasColumnType("uuid")
                        .HasColumnName("dest_port_id");

                    b.Property<Guid>("SourceAppId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_app_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("DestAppId");

                    b.HasIndex("DestPortId");

                    b.HasIndex("SourceAppId");

                    b.ToTable("app_dependencies", (string)null);
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("app_code");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("app_name");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<string>("OwnerTeam")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("owner_team");

                    b.Property<string>("Risk")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("risk");

                    b.Property<string>("TechStack")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tech_stack");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("AppCode")
                        .IsUnique();

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.Datacenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("datacenters", (string)null);
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.DependencyView", b =>
                {
                    b.Property<string>("ConnectionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("connection_type");

                    b.Property<Guid?>("DatacenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("datacenter_id");

                    b.Property<string>("DestAppCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dest_app_code");

                    b.Property<Guid>("DestAppId")
                        .HasColumnType("uuid")
                        .HasColumnName("dest_app_id");

                    b.Property<string>("DestAppName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dest_app_name");

                    b.Property<int>("DestPortNumber")
                        .HasColumnType("integer")
                        .HasColumnName("dest_port_number");

                    b.Property<string>("DestServerHostname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dest_server_hostname");

                    b.Property<string>("Environment")
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<string>("SourceAppCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_app_code");

                    b.Property<Guid>("SourceAppId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_app_id");

                    b.Property<string>("SourceAppName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_app_name");

                    b.ToTable((string)null);

                    b.ToView("v_dependency_graph", (string)null);
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.Label", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.ToTable("labels", (string)null);
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.PortMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AppId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_id");

                    b.Property<int>("PortNumber")
                        .HasColumnType("integer")
                        .HasColumnName("port_number");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("protocol");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("ServerId");

                    b.ToTable("port_mappings", (string)null);
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.Server", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DatacenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("datacenter_id");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hostname");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<string>("OsType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("os_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("DatacenterId");

                    b.HasIndex("IpAddress")
                        .IsUnique();

                    b.ToTable("servers", (string)null);
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.TopologyNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("Height")
                        .HasColumnType("double precision")
                        .HasColumnName("height");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("node_type");

                    b.Property<Guid?>("ParentNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_node_id");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<double?>("Width")
                        .HasColumnType("double precision")
                        .HasColumnName("width");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<double>("X")
                        .HasColumnType("double precision")
                        .HasColumnName("x");

                    b.Property<double>("Y")
                        .HasColumnType("double precision")
                        .HasColumnName("y");

                    b.HasKey("Id");

                    b.HasIndex("ParentNodeId");

                    b.ToTable("topology_nodes", (string)null);
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.TopologyView", b =>
                {
                    b.Property<string>("AppCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("app_code");

                    b.Property<Guid>("AppId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_id");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("app_name");

                    b.Property<Guid>("DatacenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("datacenter_id");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<int>("PortNumber")
                        .HasColumnType("integer")
                        .HasColumnName("port_number");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("protocol");

                    b.Property<string>("ServerHostname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("server_hostname");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<string>("ServerIp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("server_ip");

                    b.ToTable((string)null);

                    b.ToView("v_topology_map", (string)null);
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("server_labels", b =>
                {
                    b.Property<Guid>("LabelsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServersId")
                        .HasColumnType("uuid");

                    b.HasKey("LabelsId", "ServersId");

                    b.HasIndex("ServersId");

                    b.ToTable("server_labels");
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.AppDependency", b =>
                {
                    b.HasOne("AuditNode.Domain.Entities.Application", "DestinationApplication")
                        .WithMany("DestinationDependencies")
                        .HasForeignKey("DestAppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditNode.Domain.Entities.PortMapping", "DestinationPort")
                        .WithMany("AppDependencies")
                        .HasForeignKey("DestPortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditNode.Domain.Entities.Application", "SourceApplication")
                        .WithMany("SourceDependencies")
                        .HasForeignKey("SourceAppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DestinationApplication");

                    b.Navigation("DestinationPort");

                    b.Navigation("SourceApplication");
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.PortMapping", b =>
                {
                    b.HasOne("AuditNode.Domain.Entities.Application", "Application")
                        .WithMany("PortMappings")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditNode.Domain.Entities.Server", "Server")
                        .WithMany("PortMappings")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.Server", b =>
                {
                    b.HasOne("AuditNode.Domain.Entities.Datacenter", "Datacenter")
                        .WithMany("Servers")
                        .HasForeignKey("DatacenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Datacenter");
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.TopologyNode", b =>
                {
                    b.HasOne("AuditNode.Domain.Entities.TopologyNode", "ParentNode")
                        .WithMany("ChildNodes")
                        .HasForeignKey("ParentNodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentNode");
                });

            modelBuilder.Entity("server_labels", b =>
                {
                    b.HasOne("AuditNode.Domain.Entities.Label", null)
                        .WithMany()
                        .HasForeignKey("LabelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditNode.Domain.Entities.Server", null)
                        .WithMany()
                        .HasForeignKey("ServersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.Application", b =>
                {
                    b.Navigation("DestinationDependencies");

                    b.Navigation("PortMappings");

                    b.Navigation("SourceDependencies");
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.Datacenter", b =>
                {
                    b.Navigation("Servers");
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.PortMapping", b =>
                {
                    b.Navigation("AppDependencies");
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.Server", b =>
                {
                    b.Navigation("PortMappings");
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.TopologyNode", b =>
                {
                    b.Navigation("ChildNodes");
                });
#pragma warning restore 612, 618
        }
    }
}
