// <auto-generated />
using System;
using AuditNode.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuditNode.Infrastructure.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    partial class AuditDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuditNode.Domain.Entities.AppDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConnectionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("connection_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DestAppId")
                        .HasColumnType("uuid")
                        .HasColumnName("dest_app_id");

                    b.Property<Guid>("DestPortId")
                        .HasColumnType("uuid")
                        .HasColumnName("dest_port_id");

                    b.Property<Guid>("SourceAppId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_app_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.HasIndex("WorkspaceId", "DestAppId");

                    b.HasIndex("WorkspaceId", "DestPortId");

                    b.HasIndex("WorkspaceId", "SourceAppId", "DestAppId", "DestPortId")
                        .IsUnique();

                    b.ToTable("app_dependencies", (string)null);
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("app_code");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("app_name");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<string>("OwnerTeam")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("owner_team");

                    b.Property<string>("Risk")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("risk");

                    b.Property<string>("TechStack")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tech_stack");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "AppCode")
                        .IsUnique();

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.ApplicationLabel", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<Guid>("LabelId")
                        .HasColumnType("uuid")
                        .HasColumnName("label_id");

                    b.HasKey("WorkspaceId", "ApplicationId", "LabelId");

                    b.HasIndex("WorkspaceId", "LabelId");

                    b.ToTable("application_labels", (string)null);
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.Datacenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("datacenters", (string)null);
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.DependencyView", b =>
                {
                    b.Property<string>("ConnectionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("connection_type");

                    b.Property<Guid?>("DatacenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("datacenter_id");

                    b.Property<string>("DestAppCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dest_app_code");

                    b.Property<Guid>("DestAppId")
                        .HasColumnType("uuid")
                        .HasColumnName("dest_app_id");

                    b.Property<string>("DestAppName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dest_app_name");

                    b.Property<int>("DestPortNumber")
                        .HasColumnType("integer")
                        .HasColumnName("dest_port_number");

                    b.Property<string>("DestServerHostname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dest_server_hostname");

                    b.Property<string>("Environment")
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<string>("SourceAppCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_app_code");

                    b.Property<Guid>("SourceAppId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_app_id");

                    b.Property<string>("SourceAppName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_app_name");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.ToTable((string)null);

                    b.ToView("v_dependency_graph", (string)null);
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.Label", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Key", "Value");

                    b.ToTable("labels", (string)null);
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.PortMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AppId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_id");

                    b.Property<int>("PortNumber")
                        .HasColumnType("integer")
                        .HasColumnName("port_number");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("protocol");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "AppId");

                    b.HasIndex("WorkspaceId", "ServerId", "PortNumber")
                        .IsUnique();

                    b.ToTable("port_mappings", (string)null);
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.Server", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DatacenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("datacenter_id");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hostname");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<string>("OsType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("os_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "DatacenterId");

                    b.HasIndex("WorkspaceId", "IpAddress")
                        .IsUnique();

                    b.ToTable("servers", (string)null);
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.ServerLabel", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<Guid>("LabelId")
                        .HasColumnType("uuid")
                        .HasColumnName("label_id");

                    b.HasKey("WorkspaceId", "ServerId", "LabelId");

                    b.HasIndex("WorkspaceId", "LabelId");

                    b.ToTable("server_labels", (string)null);
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.TopologyEdge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EdgeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("edge_type");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<string>("SourceHandle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_handle");

                    b.Property<Guid>("SourceNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_node_id");

                    b.Property<string>("TargetHandle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_handle");

                    b.Property<Guid>("TargetNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_node_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "TargetNodeId");

                    b.HasIndex("WorkspaceId", "SourceNodeId", "TargetNodeId", "SourceHandle", "TargetHandle")
                        .IsUnique();

                    b.ToTable("topology_edges", (string)null);
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.TopologyNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("Height")
                        .HasColumnType("double precision")
                        .HasColumnName("height");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("node_type");

                    b.Property<Guid?>("ParentNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_node_id");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<double?>("Width")
                        .HasColumnType("double precision")
                        .HasColumnName("width");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<double>("X")
                        .HasColumnType("double precision")
                        .HasColumnName("x");

                    b.Property<double>("Y")
                        .HasColumnType("double precision")
                        .HasColumnName("y");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.HasIndex("WorkspaceId", "ParentNodeId");

                    b.ToTable("topology_nodes", (string)null);
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.TopologyView", b =>
                {
                    b.Property<string>("AppCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("app_code");

                    b.Property<Guid>("AppId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_id");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("app_name");

                    b.Property<Guid>("DatacenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("datacenter_id");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<int>("PortNumber")
                        .HasColumnType("integer")
                        .HasColumnName("port_number");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("protocol");

                    b.Property<string>("ServerHostname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("server_hostname");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<string>("ServerIp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("server_ip");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.ToTable((string)null);

                    b.ToView("v_topology_map", (string)null);
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsPersonal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_personal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId")
                        .IsUnique()
                        .HasFilter("is_personal = true");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.WorkspaceMember", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.Property<string>("InvitedByUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("invited_by_user_id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("role");

                    b.HasKey("WorkspaceId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("workspace_members", null, t =>
                        {
                            t.HasCheckConstraint("ck_workspace_members_role", "role IN ('workspace_admin', 'editor', 'auditor', 'viewer')");
                        });
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.AppDependency", b =>
                {
                    b.HasOne("AuditNode.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AuditNode.Domain.Entities.Application", "DestinationApplication")
                        .WithMany("DestinationDependencies")
                        .HasForeignKey("WorkspaceId", "DestAppId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditNode.Domain.Entities.PortMapping", "DestinationPort")
                        .WithMany("AppDependencies")
                        .HasForeignKey("WorkspaceId", "DestPortId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditNode.Domain.Entities.Application", "SourceApplication")
                        .WithMany("SourceDependencies")
                        .HasForeignKey("WorkspaceId", "SourceAppId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DestinationApplication");

                    b.Navigation("DestinationPort");

                    b.Navigation("SourceApplication");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.Application", b =>
                {
                    b.HasOne("AuditNode.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.ApplicationLabel", b =>
                {
                    b.HasOne("AuditNode.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AuditNode.Domain.Entities.Application", "Application")
                        .WithMany("ApplicationLabels")
                        .HasForeignKey("WorkspaceId", "ApplicationId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditNode.Domain.Entities.Label", "Label")
                        .WithMany("ApplicationLabels")
                        .HasForeignKey("WorkspaceId", "LabelId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Label");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.Datacenter", b =>
                {
                    b.HasOne("AuditNode.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.Label", b =>
                {
                    b.HasOne("AuditNode.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.PortMapping", b =>
                {
                    b.HasOne("AuditNode.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AuditNode.Domain.Entities.Application", "Application")
                        .WithMany("PortMappings")
                        .HasForeignKey("WorkspaceId", "AppId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditNode.Domain.Entities.Server", "Server")
                        .WithMany("PortMappings")
                        .HasForeignKey("WorkspaceId", "ServerId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Server");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.Server", b =>
                {
                    b.HasOne("AuditNode.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AuditNode.Domain.Entities.Datacenter", "Datacenter")
                        .WithMany("Servers")
                        .HasForeignKey("WorkspaceId", "DatacenterId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Datacenter");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.ServerLabel", b =>
                {
                    b.HasOne("AuditNode.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AuditNode.Domain.Entities.Label", "Label")
                        .WithMany("ServerLabels")
                        .HasForeignKey("WorkspaceId", "LabelId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditNode.Domain.Entities.Server", "Server")
                        .WithMany("ServerLabels")
                        .HasForeignKey("WorkspaceId", "ServerId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Label");

                    b.Navigation("Server");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.TopologyEdge", b =>
                {
                    b.HasOne("AuditNode.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AuditNode.Domain.Entities.TopologyNode", "SourceNode")
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "SourceNodeId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AuditNode.Domain.Entities.TopologyNode", "TargetNode")
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "TargetNodeId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceNode");

                    b.Navigation("TargetNode");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.TopologyNode", b =>
                {
                    b.HasOne("AuditNode.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AuditNode.Domain.Entities.TopologyNode", "ParentNode")
                        .WithMany("ChildNodes")
                        .HasForeignKey("WorkspaceId", "ParentNodeId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentNode");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.WorkspaceMember", b =>
                {
                    b.HasOne("AuditNode.Domain.Entities.Workspace", "Workspace")
                        .WithMany("Members")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.Application", b =>
                {
                    b.Navigation("ApplicationLabels");

                    b.Navigation("DestinationDependencies");

                    b.Navigation("PortMappings");

                    b.Navigation("SourceDependencies");
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.Datacenter", b =>
                {
                    b.Navigation("Servers");
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.Label", b =>
                {
                    b.Navigation("ApplicationLabels");

                    b.Navigation("ServerLabels");
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.PortMapping", b =>
                {
                    b.Navigation("AppDependencies");
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.Server", b =>
                {
                    b.Navigation("PortMappings");

                    b.Navigation("ServerLabels");
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.TopologyNode", b =>
                {
                    b.Navigation("ChildNodes");
                });

            modelBuilder.Entity("AuditNode.Domain.Entities.Workspace", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
